#schematics:
#  air1: #Name
#    file: 'air1.schem' #file
#    ignore-air-blocks: true
#    offsets-x: 0 # offset
#    offsets-y: 0
#    offsets-z: 0
#    replace-blocks: # replace blocks in schematic when spawning
#      BARRIER: AIR
schematics:
